### ISSUE TITLE
Pause blinks screen 

### ISSUE THREAD

**Issue by yancouto** [uspgamedev/Project-Telos#17]
When you pause, the game screen blinks black for a moment. This should not happen.

**Comment by rilifon** [comment]
I think I found the bug source!
When changing gamestates, the other gamestate will only be called after a love step has ocurred. Until then, the "current gamestate" is nothing, so the draw function will draw nothing. This occurs for a fraction of a second, but you can notice it.

A possible solution: on a gamestate leave, use canvas to take a "printscreen" on current gamestate, and make love.draw() print this canvas until you enter the next gamestate.
